#PostgreSQL Database Configuration

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: sebastian
  password: 
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: NewsApp_development

test:
  <<: *default
  database: NewsApp_test

production: 
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ivbrxlznebujoc
  password: 8df9c9063260de42c37ff268d5e8f3cfdec7e43b35bb69ac291c2d99dfd71c9b
  host: ec2-23-23-142-5.compute-1.amazonaws.com
  port: 5432
  database: ddms1jrgq9q33e
