#MySQL Database Configuration


default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: NewsApp_development

test:
  <<: *default
  database: NewsApp_test

production:
  <<: *default
  database: ENV['CLEARDB_DATABASE_URL']
  username: ENV['CLEARDB_DATABASE_USERNAME']
  password: ENV['CLEARDB_DATABASE_PASSWORD']
